language: node_js

node_js:
  - '9'

cache:
  directories:
    - node_modules

script:
  - if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    git config user.name 'Travis CI';
    git config user.email 'i@zhuweiyou.com';
    git push https://${GITEE_TOKEN}@gitee.com/game-helper/eleme.git master -f;

    cd web;
    npm i;
    npm run build;

    cd ..;
    npm run publish;
    fi

branches:
  only:
    - master
